### ISSUE TITLE
在 Worker 详情页 -> Trigger -> Custom Domains 中为这个 Worker 添加一个自定义域名

### ISSUE THREAD

**Issue by coder2z** [barretlee/cloudflare-proxy#1]
请问这一步有具体的操作方法吗？

**Comment by barretlee** [comment]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/2698003/229432740-47c342f2-88b5-4974-a666-87968f340987.png">

你可以先买一个域名，便宜的域名一年 9 块钱，然后将域名的解析迁移到 Cloudflare。然后在上图的位置进行配置就好啦。

**Comment by coder2z** [comment]
我有自己的域名我尝试一下
