### ISSUE TITLE
关于OpenAI API的调用

### ISSUE THREAD

**Issue by giphoneix** [barretlee/cloudflare-proxy#2]
非常感激作者提供这套解决方案。已经轻松实现第三方客户端的访问，感激！另外一个主要场景是代码里面调用OpenAI的API，不知道这套方案是否支持这样操作呢？

**Comment by barretlee** [comment]
没具体研究，感觉应该也很容易实现，你翻一下 openai 的源码，看看是不是有个位置定义了 request host，你覆盖下这个配置，将其修改为代理地址就好了，应该挺容易实现的。

**Comment by giphoneix** [comment]
和我的思路一样，确实正如阁下所言。感谢🙏

**Comment by lazy2panda** [comment]
如果使用openai的官方python包可以这样设置自定义地址：
import os
os.environ["OPENAI_API_BASE"]="https://YOUR_HOST_NAME/v1"

**Comment by giphoneix** [comment]
谢谢，这个办法比改api文件好，厉害啊 👍
