### ISSUE TITLE
第三方客户端无法使用

### ISSUE THREAD

**Issue by l0g1n** [barretlee/cloudflare-proxy#3]
感谢楼主，已成功搭建好，使用OpenCat正常使用。

Win上面没有对应客户端，使用浏览器插件
https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?hl=zh-CN

https://github.com/chathub-dev/chathub

会出现跨域错误，调试了好久，没能解决。

求助一下。

**Comment by l0g1n** [comment]
在ChatGPT的帮助下，解决了这个问题。
![image](https://user-images.githubusercontent.com/7485747/229661137-6134fe2e-768f-41e8-a8e1-9626373e2de9.png)

**Comment by barretlee** [comment]
感谢补充，我完善下脚本

**Comment by alanfugit** [comment]
如果配置域名不用https，用postman会报 The OpenAI API can only be accessed over HTTPS. 错误 ，如果用客户端，直接配域名就能用，是什么原因？

**Comment by barretlee** [comment]
> 如果配置域名不用https，用postman会报 The OpenAI API can only be accessed over HTTPS. 错误 ，如果用客户端，直接配域名就能用，是什么原因？

抱歉，后面半截没看明白。postman 的报错是 OpenAI throw 出来的，原因说的很清楚，必须 HTTPS；客户端请求没问题，那说明一定用了 HTTPS 协议。
