### ISSUE TITLE
got   403 Forbidden on cloudflare

### ISSUE THREAD

**Issue by lazy2panda** [barretlee/cloudflare-proxy#8]
我在cloudflare部署cloudflare-worker.js 的时候发现报错403 Forbidden，是哪里配置不对吗？
![image](https://user-images.githubusercontent.com/7948261/230592279-c6b74bec-b31d-49d8-a3ab-1dfd82099bb9.png)

**Comment by barretlee** [comment]
GET 请求不带 bearer 信息，肯定 403 咯。参考这个：
<img width="462" alt="image" src="https://user-images.githubusercontent.com/2698003/230637315-61c093fe-2f69-4535-b74c-ec873e0f5333.png">

**Comment by lazy2panda** [comment]
> GET 请求不带 bearer 信息，肯定 403 咯。参考这个： <img alt="image" width="462" src="https://user-images.githubusercontent.com/2698003/230637315-61c093fe-2f69-4535-b74c-ec873e0f5333.png">

可以了，感谢
